### ISSUE TITLE
How to test in TESTNET

### ISSUE THREAD

**Issue by martudev** [jeffersonlicet/price-prediction-bot#3]
Hi! How are you? I would like to ask you how I can test the bot on the testnet, since the pancakeswap contract is not found on the testnet, it occurred to me to fork the mainet to my localnet with ganache-cli, but unfortunately it is not constantly synchronized with the mainnet so the new generated blocks are not in my localnet. I hope it can be done, thank you in advance

**Comment by jeffersonlicet** [comment]
I don't think you will be able to do that.  That's the main reason of this project, to run backtest without losing money

**Comment by martudev** [comment]
ok so thanks for all!! and very nice project!!
